name: Build and Release Rust Project

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust for Windows
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Install dependencies
      run: cargo fetch

    - name: Build
      run: cargo build --release

    - name: Upload artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: windows-latest-build
        path: target/release/arnis.exe

  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Windows build artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-latest-build
        path: ./builds/windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          builds/windows/arnis.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
